import streamlit as st
import pandas as pd
import numpy as np
import os
import google.generativeai as genai

def get_gemini_client():
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        if 'gemini_api_key' in st.session_state:
            api_key = st.session_state['gemini_api_key']
    if api_key:
        try:
            genai.configure(api_key=api_key)
            return genai.GenerativeModel("gemini-2.5-flash")
        except Exception as e:
            st.error(f"Failed to configure Gemini Client: {e}")
    return None

def show_optimizer_page():
    st.markdown("<h1>📅 Dynamic Wellness <span class='neon-text'>Schedule Optimizer</span></h1>", unsafe_allow_html=True)
    st.markdown("<p style='font-size: 16px; color: #94a3b8;'>Formulate optimized daily teenage schedules balancing digital time, academics, fitness, and restorative sleep.</p>", unsafe_allow_html=True)

    # API key check
    if not os.environ.get("GEMINI_API_KEY") and 'gemini_api_key' not in st.session_state:
        st.warning("⚠️ Google AI Studio API Key is required to execute Generative Schedule Optimizations. Please enter your API Key in the Gemini Psychology Copilot tab.")
        return

    model = get_gemini_client()
    if model is None:
        st.error("Gemini API configured but client initialization failed. Please configure your key in the Gemini Psychology Copilot tab.")
        return

    # Diagnostic data load
    df_diag = st.session_state.get('last_diagnostic_input')
    risk_prob = st.session_state.get('last_risk_probability')

    # Two column layout: Left for tuning controls, Right for AI Wellness Schedule
    col_controls, col_schedule = st.columns([1, 1])

    with col_controls:
        st.markdown("<div class='glass-card'><h3>🛠️ Wellness Tuning Parameters</h3><p style='font-size:12px;color:#94a3b8;'>Adjust targeted clinical intervention dials to skew schedule calculations.</p></div>", unsafe_allow_html=True)
        
        focus_goal = st.selectbox(
            "Primary Intervention Focus",
            [
                "Balanced Lifestyle Restructuring (General Wellness)",
                "Sleep Recovery Protocol (High Sleep Disruption Focus)",
                "Cognitive studious focus (GPA and Test Anxiety Mitigation)",
                "Physical Activation Diet (Low Exercise & Sedentary Habit Focus)"
            ]
        )
        
        screen_allowance = st.slider(
            "Strict Social Media Limit (daily hours)",
            min_value=0.5,
            max_value=4.0,
            value=1.5,
            step=0.5
        )
        
        bedtime_routine = st.selectbox(
            "Pre-Bed Screen Lock Window",
            [
                "60 Minutes Before Sleep (Standard)",
                "90 Minutes Before Sleep (Advised for Sleep Disruption)",
                "120 Minutes Before Sleep (Clinical Clinical Recovery)"
            ]
        )

        physical_target = st.slider(
            "Target Daily Movement / Fitness (hours)",
            min_value=0.5,
            max_value=3.0,
            value=1.0,
            step=0.5
        )

        st.markdown("<h5 style='color:#00f2fe; margin-top:20px;'>📥 Loaded Teen Profile Context</h5>", unsafe_allow_html=True)
        if df_diag is not None:
            st.markdown(
                f"<div style='padding: 10px; background-color: rgba(30, 41, 59, 0.4); border-radius: 6px; font-size:13px;'>"
                f"Active Profile: <strong>{df_diag.iloc[0]['age']}-year-old</strong> "
                f"diagnosed with <strong>{risk_prob*100:.1f}% risk</strong> of depression burden.<br>"
                f"Current habits: Daily hours: {df_diag.iloc[0]['daily_social_media_hours']:.1f}h, "
                f"Sleep: {df_diag.iloc[0]['sleep_hours']:.1f}h, GPA: {df_diag.iloc[0]['academic_performance']:.2f}"
                f"</div>",
                unsafe_allow_html=True
            )
        else:
            st.info("ℹ️ No diagnostic teenager profile loaded. Schedule will optimize based on general psychiatric health standards.")

        optimize_btn = st.button("🪄 Calculate Optimized Daily Schedule")

    with col_schedule:
        st.markdown("<div class='glass-card'><h3>📅 Healthy Youth Daily Plan</h3><p style='font-size:12px;color:#94a3b8;'>Custom timeline generated by Gemini wellness reasoning agent.</p></div>", unsafe_allow_html=True)
        
        if optimize_btn:
            # Construct prompting model
            profile_context = ""
            if df_diag is not None:
                profile_context = f"""
                Individual Teenager Profile:
                - Age: {df_diag.iloc[0]['age']}
                - Gender: {df_diag.iloc[0]['gender']}
                - Current Screen Hours: {df_diag.iloc[0]['daily_social_media_hours']:.1f} hours/day
                - Current Sleep: {df_diag.iloc[0]['sleep_hours']:.1f} hours/night (with pre-sleep screen exposure: {df_diag.iloc[0]['screen_time_before_sleep']:.1f} hours)
                - Current GPA: {df_diag.iloc[0]['academic_performance']:.2f}/4.00
                - Current Daily Exercise: {df_diag.iloc[0]['physical_activity']:.1f} hours/day
                - Measured Mental Health Risk: {risk_prob*100:.2f}% (High Risk if >65%, Moderate if >25%)
                """
            else:
                profile_context = "Cohort focus: Typical teenager experiencing heavy social media exposure, mild sleep disruption, and academic stress."

            prompt = f"""
            You are playing the role of an expert Pediatric Digital Health Architect and Youth Wellness Planner.
            You are designing an optimized, healthy, complete 24-hour daily timeline/schedule for an adolescent.
            The goal is to balance studying, offline social interaction, physical exercise, and restorative sleep while strictly containing screen habits.
            
            Inputs:
            {profile_context}
            
            Tuning Parameters Chosen:
            - Primary Goal: {focus_goal}
            - Strict Social Media Time Limit: {screen_allowance} hours/day
            - Pre-bed Screen Lock Window: {bedtime_routine}
            - Target Daily Movement: {physical_target} hours/day

            Please output a highly structured daily timeline in a beautiful Markdown Table format.
            Include three columns:
            1. Time Slot (e.g. 07:00 AM - 08:00 AM)
            2. Recommended Youth Activity (Action-oriented, e.g. Hydrate & Out-of-bedroom Stretching)
            3. Psychological Benefit & Digital Rule (Clinical reasoning behind the slot, e.g. Cortisol regulation, Screen Lock active 🚫)

            Followed by 3 brief clinical "Digital Diet Tips" explaining how parents can enforce this plan. Keep it structured, highly polished, and visually stunning.
            """

            with st.spinner("Calculating schedule and balancing digital diet..."):
                try:
                    response = model.generate_content(prompt)
                    st.markdown(response.text)
                    st.text_area("Copy Timeline Markdown", value=response.text, height=180)
                except Exception as e:
                    st.error(f"Error calling Gemini for wellness schedule: {e}")
        else:
            st.markdown(
                """
                <div style='text-align: center; padding: 50px 20px; border: 1px dashed rgba(255,255,255,0.1); border-radius: 12px; background-color: rgba(30, 41, 59, 0.2);'>
                <p style='font-size: 32px;'>📅</p>
                <h4 style='color: #64748b; margin-top:0px;'>Schedule Timeline Uncalculated</h4>
                <p style='color: #64748b; font-size: 13px;'>Adjust parameters on the left and click "Calculate Optimized Daily Schedule" to construct the wellness plan.</p>
                </div>
                """,
                unsafe_allow_html=True
            )
st.markdown("---")
